### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wildone** [websight-io/starter#153]
**Description**
Currently, an error is being dumped into the error log, I wonder if you see this? I cant see any specific reason this happens.

```
30.03.2023 12:00:20.091 *ERROR* [sling-default-4-Sling Models OSGi Service Disposal Job] org.apache.sling.commons.scheduler.impl.QuartzScheduler Exception during job execution of job 'org.apache.sling.models.impl.ModelAdapterFactory@5149c630' with name 'Sling Models OSGi Service Disposal Job' : Invalid BundleContext.
java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:491)
	at org.apache.felix.framework.BundleContextImpl.ungetService(BundleContextImpl.java:455)
	at org.apache.sling.models.impl.injectors.OSGiServiceInjector$Callback.onDisposed(OSGiServiceInjector.java:204) [org.apache.sling.models.impl:1.5.0]
	at org.apache.sling.models.impl.ModelAdapterFactory$DisposalCallbackRegistryImpl.onDisposed(ModelAdapterFactory.java:143) [org.apache.sling.models.impl:1.5.0]
	at org.apache.sling.models.impl.ModelAdapterFactory.clearDisposalCallbackRegistryQueue(ModelAdapterFactory.java:214) [org.apache.sling.models.impl:1.5.0]
	at org.apache.sling.models.impl.ModelAdapterFactory.run(ModelAdapterFactory.java:206) [org.apache.sling.models.impl:1.5.0]
	at org.apache.sling.commons.scheduler.impl.QuartzJobExecutor.execute(QuartzJobExecutor.java:349) [org.apache.sling.commons.scheduler:2.7.12]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202) [org.apache.sling.commons.scheduler:2.7.12]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by wildone** [comment]
Testing on 1.12 now :D
